# fly-deploy-stage.yml
# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy to Stage
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app to Stage
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: https://my-remix-app-fragrant-stage.fly.dev
    concurrency: deploy-group-stage    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -a my-remix-app-fragrant-stage -c fly-deploy-stage.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}